# Node.js with React
# Build a Node.js application that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.11.4"
    displayName: "Install Node.js"

  - script: |
      yarn
      yarn test
    displayName: "yarn install and test"
